options:
  formatter: stylish

rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 2

  # Mixins
  mixins-before-declarations:
    - 2
    - exclude:
        - media-query

  # BEM
  bem-depth:
    - 2
    - max-depth: 2

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 2
  single-line-per-selector: 1

  class-name-format:
    - 1
    - convention: hyphenatedbem

  # Disallows
  no-color-keywords: 2
  no-color-literals:
    - 1
    - allow-rgba: true
  no-css-comments: 1
  no-duplicate-properties: 2
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 2
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
  no-trailing-zero: 1

  # Nesting
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1

  # Indentation
  indentation: #
    - 2
    - size: 2

  # Name Formats
  function-name-format: 2
  mixin-name-format:
    - 2
  placeholder-name-format: 1
  variable-name-format:
    - 2
    - allow-leading-underscore: false
  no-vendor-prefixes:
    - 1
    - excluded-identifiers:
        - webkit
        - moz

  # Style Guide
  border-zero:
    - 0
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: true
  clean-import-paths: 2
  empty-args: 1
  hex-length: 2
  hex-notation: 2
  leading-zero:
    - 1
    - include: true
  nesting-depth:
    - 2
    - max-depth: 3
  property-sort-order:
    - 1
    - order: alphabetical
  quotes:
    - 1
    - style: single
  zero-unit:
    - 1
    - include: false

  # Inner Spacing
  space-after-comma:
    - 1
    - include: true
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1

  # Final Items
  trailing-semicolon: 1
  final-newline:
    - 1
    - include: true
